## 분석용 기초
### NumPy 계속

In [172]:
import numpy as np

In [173]:
# Python 리스트를 생성 -> 넘파이 배열로 변경
a = [1,3,5,7,9]
na = np.array(a)

In [174]:
a

[1, 3, 5, 7, 9]

In [175]:
print(a)

[1, 3, 5, 7, 9]

In [176]:
na

array([1, 3, 5, 7, 9])

In [177]:
print(na)

[1 3 5 7 9]

In [178]:
nb = np.array([
    [1,2,3],
    [4,5,6]
]) # 2행 3열 2차원 배열

In [179]:
# 2차원 배열 nb의 1번행을 추출
nb[1]

array([4, 5, 6])

In [180]:
nb[1, 2] # nb의 1번행, 2번열을 추출

np.int64(6)

- Python의 기본형 int Numpy에서 np.int64형과 동일

In [181]:
nc = np.array([1.2,2.3,3.4])
nc[1]

np.float64(2.3)

- python의 float은 NumPy에서는 np.float64

In [182]:
nb.sum() # 행렬 모든 요소 합산

np.int64(21)

In [183]:
nb.sum(axis=0) #열 기준으로 합산

array([5, 7, 9])

In [184]:
nb.sum(axis=1) # 행기준으로 합산

array([ 6, 15])

In [185]:
# 랜덤 데이터 생성
np.random.rand(5)

array([0.36089434, 0.07269967, 0.82608674, 0.26341998, 0.34347795])

In [186]:
np.random.randint(1, 10, 5)

array([7, 5, 8, 9, 8], dtype=int32)

In [187]:
#정규화
nd = np.array([10, 20, 30])

normalrized = (nd - nd.mean()) / nd.std()
normalrized

array([-1.22474487,  0.        ,  1.22474487])

In [188]:
# 점수데이터 합격자만 추출
scores = np.array([50,80,90,60,30])

scores[scores >= 60]

array([80, 90, 60])

In [189]:
scores.mean()

np.float64(62.0)

- 정리
    - list: 파이썬 for문 사용
    - Numpy:

In [190]:
!pip install pandas

Requirement already satisfied: pandas in c:\sourcebank\iot_python-2026\iot-venv\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\sourcebank\iot_python-2026\iot-venv\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\sourcebank\iot_python-2026\iot-venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\sourcebank\iot_python-2026\iot-venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\sourcebank\iot_python-2026\iot-venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [191]:
!pip install pandas

Requirement already satisfied: pandas in c:\sourcebank\iot_python-2026\iot-venv\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\sourcebank\iot_python-2026\iot-venv\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\sourcebank\iot_python-2026\iot-venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\sourcebank\iot_python-2026\iot-venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\sourcebank\iot_python-2026\iot-venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [192]:
!pip list

Package                 Version
----------------------- -----------
asttokens               3.0.1
colorama                0.4.6
comm                    0.2.3
debugpy                 1.8.20
decorator               5.2.1
et_xmlfile              2.0.0
executing               2.2.1
ipykernel               7.2.0
ipython                 9.12.0
ipython_pygments_lexers 1.1.1
jedi                    0.19.2
jupyter_client          8.8.0
jupyter_core            5.9.1
matplotlib-inline       0.2.1
nest-asyncio            1.6.0
numpy                   2.4.4
openpyxl                3.1.5
packaging               26.0
pandas                  3.0.1
parso                   0.8.6
pip                     25.0.1
platformdirs            4.9.4
prompt_toolkit          3.0.52
psutil                  7.2.2
pure_eval               0.2.3
Pygments                2.20.0
python-dateutil         2.9.0.post0
pyzmq                   27.1.0
six                     1.17.0
stack-data              0.6.3
tornado                 6.5.5
traitlets               5.14.3
tzdata                  2025.3
wcwidth                 0.6.0

판다스 기초

- 핵심구조
    - DataFrame(데이터프레임) : 기준. 2차원 배열
    - Series(시리즈): 최소원소, 1차원 배열

In [193]:
# 판다스 라이브러리 로드
import pandas as pd

In [194]:
# 시리즈
s1 = pd.Series([10,20,30])
s1

0    10
1    20
2    30
dtype: int64

In [195]:
[10, 20, 30]

[10, 20, 30]

In [196]:
# 데이터프레임
# 딕셔너리 타입
data = {
    'name': ['유고', '요미', '철수'],
    'score': [90, 100, 36]
}
data

{'name': ['유고', '요미', '철수'], 'score': [90, 100, 36]}

### 데이터프레임은 엑셀처럼 내놓는다

In [197]:
# 데이터프레임
df = pd.DataFrame(data)
df

  name  score
0   유고     90
1   요미    100
2   철수     36

#### 데이터 확인 및 편집
- 데이터 분석시 필요한 및 핵심기술

In [198]:
# CSV 읽기
df = pd.read_csv('./도서정보.csv', encoding='utf-8')
df

,번호,서명,저자,발행자,발행년,청구기호,자료실
0,1,해럴드와 마법 크레용 [비디오녹화자료],카를로스 살다냐 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2246,[해운대인문학]디지털자료실
1,2,나처럼 예쁜 여자 [비디오녹화자료],프랑수아 트뤼포 감독,Art Film [수입·제조],2024,DVD 688.2-2247,[해운대인문학]디지털자료실
2,3,조커 [비디오녹화자료] : 폴리 아 되,토드 필립스 감독,해리슨 앤 컴퍼니 [제조·판매],[2025],DVD 688.2-2248,[해운대인문학]디지털자료실
3,4,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 2, 싹트는 울음소리, 뿌리 괴수의 진실",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-2,[해운대인문학]디지털자료실
4,5,마당을 나온 암탉 [비디오녹화자료],오성윤 감독,미디어포유 [제작·판매],2025,DVD 688.6-335=2,[해운대인문학]디지털자료실
5,6,더 파일럿 [비디오녹화자료] : 드론 어택,폴 듀세 감독,미디어포유 [제작·판매],2025,DVD 688.2-2249,[해운대인문학]디지털자료실
6,7,새터데이 나이트 [비디오녹화자료],제이슨 라이트먼 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2250,[해운대인문학]디지털자료실
7,8,구룡성채 [비디오녹화자료] : 무법지대,정바오루이 감독,플레인아카이브 [DVD 제작·판매],[2025],DVD 688.2-2251,[해운대인문학]디지털자료실
8,9,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 3, 수상한 공사장의 비밀",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-3,[해운대인문학]디지털자료실
9,10,베리 미 트와이스 [비디오녹화자료],스티븐 라모트 감독,미디어포유 [제작],2025,DVD 688.2-2252,[해운대인문학]디지털자료실

In [199]:
# 엑셀파일 읽기
df = pd.read_excel('./sample (1).xlsx')
df

    이름   국어     영어   수학
0  홍길동   95   98.0   93
1  애슐리  100  100.0  100
2  성명건   90    NaN   78
3  김예성   50   50.0  100

- 엑셀을 읽으려면 openpyxl 모듈이 추가로 필요

```bash
!pip install openpyxl
```

- 엑셀을

In [200]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\sourcebank\iot_python-2026\iot-venv\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\sourcebank\iot_python-2026\iot-venv\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [201]:
# 데이터 확인 - 기본 상위 5개만 출력
df.head()

    이름   국어     영어   수학
0  홍길동   95   98.0   93
1  애슐리  100  100.0  100
2  성명건   90    NaN   78
3  김예성   50   50.0  100

In [202]:
df.head(3)

    이름   국어     영어   수학
0  홍길동   95   98.0   93
1  애슐리  100  100.0  100
2  성명건   90    NaN   78

In [203]:
#데이터 하위 5개
df.tail()

    이름   국어     영어   수학
0  홍길동   95   98.0   93
1  애슐리  100  100.0  100
2  성명건   90    NaN   78
3  김예성   50   50.0  100

In [204]:
#타입정보 확인
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      4 non-null      str
 1   국어      4 non-null      int64
 2   영어      3 non-null      float64
 3   수학      4 non-null      int64
dtypes: float64(1), int64(2), str(1)
memory usage: 260.0 bytes

- Null값은 통계에서 치명적인 데이터
- Null 데이터가 없도록 만들어주는 것이 데이터분석 전 핵심작업

In [205]:
# 기초 통계 기본데이터 추출. 컬럼 중 숫자형만 추출가능
df.describe()

               국어          영어          수학
count    4.000000    3.000000    4.000000
mean    83.750000   82.666667   92.750000
std     22.867371   28.307832   10.372239
min     50.000000   50.000000   78.000000
25%     80.000000   74.000000   89.250000
50%     92.500000   98.000000   96.500000
75%     96.250000   99.000000  100.000000
max    100.000000  100.000000  100.000000

In [206]:
# 컬럼 선택
#df['서명']

In [207]:
df['서명'].info()

KeyError: '서명'

In [ ]:
# 새로 데이터프레임 읽기
df = pd.read_excel('./sample (1).xlsx')
df

    이름   국어     영어   수학
0  홍길동   95   98.0   93
1  애슐리  100  100.0  100
2  성명건   90    NaN   78
3  김예성   50   50.0  100

- NaN:Not a Number

In [ ]:
# 국어 점수가 60 이상만 필터링
df['국어'] > 60

0     True
1     True
2     True
3    False
Name: 국어, dtype: bool

In [ ]:
# 60 
df[df['국어']>60]

    이름   국어     영어   수학
0  홍길동   95   98.0   93
1  애슐리  100  100.0  100
2  성명건   90    NaN   78

In [ ]:
# 영어점수가 50이상 필터링
df['영어'] >= 50

0     True
1     True
2    False
3     True
Name: 영어, dtype: bool

In [ ]:
df[df['영어']>=50]

    이름   국어   영어   수학  수학_1
0  홍길동   95   98   93    88
1  애슐리  100  100  100    95

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      4 non-null      str
 1   국어      4 non-null      int64
 2   영어      3 non-null      float64
 3   수학      4 non-null      int64
dtypes: float64(1), int64(2), str(1)
memory usage: 260.0 bytes

In [ ]:
# 여기서부터 큰일이 발생
df.describe()

               국어          영어          수학
count    4.000000    3.000000    4.000000
mean    83.750000   82.666667   92.750000
std     22.867371   28.307832   10.372239
min     50.000000   50.000000   78.000000
25%     80.000000   74.000000   89.250000
50%     92.500000   98.000000   96.500000
75%     96.250000   99.000000  100.000000
max    100.000000  100.000000  100.000000

#### 결측치(Missing Value)
- 데이터 수집과정에서 누락되거나 측정되지 않은 빈 값
- 데이터분석에서는 걸측치를 처리하는 일이 가장 중요

In [212]:
# 새 컬럼 만들기
df['수학_1'] = df['수학'] - 5

In [213]:
#정렬
df.sort_value('수학_1')

AttributeError: 'DataFrame' object has no attribute 'sort_value'

In [210]:
df.sort_values(by='수학_1', ascending=False)

KeyError: '수학_1'

In [ ]:
#걸측치 처리
df1 = df.dropna()
df1

    이름   국어   영어   수학  수학_1
0  홍길동   95   98   93    88
1  애슐리  100  100  100    95

In [ ]:
df2 = df.fillna(45)
df2

    이름   국어   영어   수학  수학_1
0  홍길동   95   98   93    88
1  애슐리  100  100  100    95

In [ ]:
#그룹화(GroupBy) - SQL이 Group By와 동일
df.groupby('수학').count()

     이름  국어  영어
수학
78    1   1   0
93    1   1   1
100   2   2   2

In [208]:
df[['국어', '영어', '수학']].fillna(45).groupby('수학').mean()

       국어    영어
수학
78   90.0  45.0
93   95.0  98.0
100  75.0  75.0

간단 예제

In [214]:
data = {
    'name': ['유고', '요미', '철수', '예성'],
    'score': [80, 95, 60, 70]
}

df = pd.DataFrame(data)
df

  name  score
0   유고     80
1   요미     95
2   철수     60
3   예성     70

In [215]:
#CSV로 쓰게
df.to_csv('./scores.csv', encoding='utf-8')

In [218]:
df['score'].mean()

np.float64(76.25)

In [216]:
# 70점 이상만 추출
df['score'] >= 70

0     True
1     True
2    False
3     True
Name: score, dtype: bool

In [217]:
df[df['score']>=70]

  name  score
0   유고     80
1   요미     95
3   예성     70

In [221]:
# 합격여부
# 리스트 컴프리헨션으로 새 컬럼 생성
df['result'] = ['PASS' if s >= 70 else 'FAIL' for s in df['score']]

In [222]:
df

  name  score result
0   유고     80   PASS
1   요미     95   PASS
2   철수     60   FAIL
3   예성     70   PASS

- 판다스 내부는 Numpy 기반임. NumPy스타일로 처리가능